# Generated by Django 3.2.16 on 2023-01-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggaransiswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='jumlah_poin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='tanggal',
            field=models.DateField(auto_now=True),
        ),
    ]
