# Generated by Django 3.2.16 on 2023-01-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggaransiswa', '0002_auto_20230112_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='jurusan',
        ),
        migrations.AlterField(
            model_name='data',
            name='tanggal',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
