# Generated by Django 3.2.16 on 2023-01-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggaransiswa', '0003_auto_20230114_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='keterangan',
            field=models.CharField(choices=[('ses', 's'), ('kesiangan', 'k')], max_length=50),
        ),
    ]
