# Generated by Django 3.2.16 on 2023-01-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggaransiswa', '0004_alter_data_keterangan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='jumlah_poin',
        ),
        migrations.AlterField(
            model_name='data',
            name='keterangan',
            field=models.CharField(max_length=50),
        ),
    ]
