# Generated by Django 3.2.16 on 2023-01-22 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggaransiswa', '0006_auto_20230122_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelanggaransiswa.data')),
            ],
        ),
    ]
