# Generated by Django 3.2.16 on 2023-01-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggaransiswa', '0007_pelanggar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Pelanggar',
            new_name='Rincian',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='nama',
            new_name='id_siswa',
        ),
        migrations.RemoveField(
            model_name='data',
            name='kelas',
        ),
    ]
