# Generated by Django 3.2.16 on 2023-01-22 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggaransiswa', '0009_siswa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='id_siswa',
        ),
        migrations.AddField(
            model_name='data',
            name='siswa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pelanggaransiswa.siswa'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nama',
            field=models.CharField(max_length=50),
        ),
    ]
