# Generated by Django 3.2.16 on 2023-01-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggaransiswa', '0011_auto_20230123_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='pelanggaran_id',
            new_name='pelanggaran',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='siswa_id',
            new_name='siswa',
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nis',
            field=models.IntegerField(),
        ),
    ]
