# Generated by Django 3.2.16 on 2023-01-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggaransiswa', '0013_alter_siswa_nis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rincian',
        ),
    ]
