# Generated by Django 3.2.16 on 2023-01-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggaransiswa', '0014_delete_rincian'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Pelanggar',
        ),
    ]
