# Generated by Django 3.2.16 on 2023-01-24 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggaransiswa', '0015_rename_data_pelanggar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rincian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pelanggar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelanggaransiswa.pelanggar')),
            ],
        ),
    ]
