# Generated by Django 3.2.16 on 2023-01-25 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggaransiswa', '0016_rincian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rincian',
            old_name='id_pelanggar',
            new_name='pelanggaran',
        ),
    ]
